#!/bin/bash
#Prepare apt-get repo
apt-get install -y apt-transport-https ca-certificates curl
curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
apt-get update
#install necessary packages
apt-get install -y kubectl
apt-get install -y kubeadm
apt-get install -y kubelet
apt-get install -y docker.io

##Config
swapoff -a
echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables
echo "1" > /proc/sys/net/ipv4/ip_forward
echo 'KUBELET_EXTRA_ARGS="--cgroup-driver=systemd"' >> /etc/default/kubelet
DIR="/home/$SUDO_USER" #Get users home directory
#Create .kube directory
mkdir -p $DIR/.kube
cp -i /etc/kubernetes/admin.conf $DIR/.kube/config
chown $(id -u):$(id -g) $DIR/.kube/config
